language: generic
sudo: required

services:
- docker

install: true

before_script:
- make build
- make build COMPOSE=docker-compose.yml.www-with-app

script:
- make run
- make test
- docker-compose down
- make run
- make test
- docker-compose down
- make run COMPOSE=docker-compose.yml.www-with-app
- make test
