name: Test Web application authentication developer setup

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 22 * * 0'

jobs:
  test-docker-compose:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose version
      - run: make build
      - run: make build COMPOSE=docker-compose.yml.www-with-app
      - run: make run
      - run: make test
      - run: docker-compose down
      - run: make run
      - run: make test
      - run: docker-compose down
      - run: make run COMPOSE=docker-compose.yml.www-with-app
      - run: make test
