name: Test Web application authentication developer setup

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 22 * * 0'

jobs:
  test-docker-compose:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -e
          echo -e "dockremap:$( id -u ):1\ndockremap:200001:65535" | sudo tee -a /etc/subuid
          echo -e "dockremap:$( id -g ):1\ndockremap:200001:65535" | sudo tee -a /etc/subgid
          echo '{ "userns-remap": "default" }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - run: docker compose version
      - run: make build
      - run: make build COMPOSE=docker-compose.yml.www-with-app
      - run: make run
      - run: make test
      - run: make stop
      - run: make run
      - run: make test
      - run: make stop
      - run: make run COMPOSE=docker-compose.yml.www-with-app
      - run: make test COMPOSE=docker-compose.yml.www-with-app

  test-podman-compose:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install podman-compose
      - run: podman-compose version
      - run: make build DOCKER_COMPOSE=podman-compose
      - run: make build DOCKER_COMPOSE=podman-compose COMPOSE=docker-compose.yml.www-with-app
      - run: make run DOCKER_COMPOSE=podman-compose
      - run: make test DOCKER_COMPOSE=podman-compose
      - run: make stop DOCKER_COMPOSE=podman-compose
      - run: make run DOCKER_COMPOSE=podman-compose
      - run: make test DOCKER_COMPOSE=podman-compose
      - run: make stop DOCKER_COMPOSE=podman-compose
      - run: make run DOCKER_COMPOSE=podman-compose COMPOSE=docker-compose.yml.www-with-app
      - run: make test DOCKER_COMPOSE=podman-compose COMPOSE=docker-compose.yml.www-with-app
